---
title: "Lab 6 Feedback"
format: html
---

# COMPLETION

## Question 5

Check histograms:

**If they don't have a good bin widht**

When deciding on a bin width for your histograms, make sure the histogram looks smoothed out and not too choppy. Try increasing your bin width to see the shape of the histogram a little better!

**If they dont' have informative or reader friendly axis labels**

Make sure to be descriptive in your histogram axis labels! What is the histogram displaying?

## Question 12 `t_test()`

**if they set mu = 2.3**

Remember mu is set equal to our null value. If there is not‘ a difference in the reading time between the two forms, what do we expect the mean of the differences in reading time to be?

**If they have an alternative of less or two-sided:**

Careful! In the hypotheses we said that the mean of the differences in read times should be greater than 0, assuming that it take people longer to read the color names when they are printed in mismatched colors than in black text.


## Question 17

**If they talk about the p-value being in the interval:**

A p-value is the probability of obtaining a mean difference of 2.46 or something larger, if there was no difference in the read times between the two formats (a mean difference of 0). The confidence interval is the range of values that we are 95% confident captures the mean difference. The confidence interval will agree with our hypothesis test, if the null value (0) is not contained in the interval! 

**If they say they don't agree:**

If the p-value is less than 0.05, we would reject the null hypothesis. If our 95% confidence interval does not include 0, then we would also reject the null hypothesis. The only way these methods would not agree is if you had a p-value less than 0.05 and your confidence interval contained 0! 

## Question 18

**If they say yes but not because of randomization:**

This statement agrees with what our analysis found, but the key aspect of their interpretation is the use of the word **CAUSE**. Can the researchers say if  printing the color names in mismatched colors CAUSED and increase in the time it took to read them? Hint: Look at the description for how they decided what order people read the two lists in. 

**If they say no because there isn't randomization:**

Look back at the description for how they decided what order people read the two lists in. In the case of paired data, we don't have a control group. Instead,each person is assigned both "treatments" -- here they read both lists. 

**If they say no because it's observational:**

Careful! Experiments have random assignment rather than us just observing the time it takes people to read two different lists of words. The researchers in this study randomly assigned which list a person read first versus second. 


# CANVAS QUIZ

## Canvas Question 2 (Lab 1)

**If they say independent**

Careful! Since we have the same student reading the words in a different color and in black text, we have natural pairing across the two groups.

## Canvas Question 3 (Lab 2)

**If they say "the difference in means":**

Caution! We are analyzing the difference in read times and taking the mean of
those differences. This is referred to as the mean of the differences **not** the
difference in means!

## Canvas Question 5 (Lab 4)

**If they say mu_color - mu_black:**

Remember, this is a paired design! Therefore we are taking the mean of the difference column and indicate this with only one mu.

**If they say (not equal to)**

Careful, what was our research question? We want to know if reading the color words in a different color INCREASES the time.

## Canvas Question 13 (Lab 14)

**If they have 0.008% instead of 0.8%**

Make sure to convert your p-value to a probability by multiplying by 100!

## Canvas Question 15 (Lab 16)

**If they have 95% instead of 99%**

Take a look at your t_text() code; what is the conf.level?



<!-- ## Question 10 -->

<!-- **If they say 0.08% chance of the null:** -->

<!-- A p-value is the probability of obtaining a mean difference of 2.46 or something -->
<!-- larger, if there was no difference in the read times between the two formats -->
<!-- (a mean difference of 0).  -->

<!-- **If they don't interpret the p-value:** -->

<!-- The question here is not about whether you would reject or fail to reject the -->
<!-- null hypothesis. Rather, you are being asked to **interpret** what the p-value -->
<!-- of 0.00812 means! Hint: it's the probability of ***assuming ***... -->

<!-- ## Question 12 -->

<!-- **If they interpret the CI with infinity:** -->

<!-- Your interpretation is correct, but it is a bit simpler to say that we are 95%  -->
<!-- confident the true mean of the differences in read times is **at least** as  -->
<!-- large as 0.744 seconds.  -->

<!-- **If they forget the units!** -->

<!-- Careful! We need to be sure to include the units associated with our confidence -->
<!-- interval -- is 0.744 in seconds? Minutes? Hours? -->

<!-- **If they use the wrong units:** -->

<!-- Careful! The units for the differences is seconds not minutes! -->

<!-- **If they say "the difference in means":** -->

<!-- Caution! We are analyzing the difference in read times and taking the mean of -->
<!-- those differences. This is referred to as the mean of the differences **not** the -->
<!-- difference in means! -->




